config/routes.rb
Rails.application.routes.draw do
  ### chat start
  # Mount the Action Cable server on a sub-URI of our main application.
  # Action Cable will be listening for WebSocket requests on ws://localhost:3000/cable. It will do so by using the Rack socket hijacking API. When our main application is instantiated, an instance of Action Cable will also be created. Action Cable will, per our instructions in the routes.rb file, establish a WebSocket connection on localhost:3000/cable, and begin listening for socket requests on that URI.
  mount ActionCable.server => '/cable'
  ### chat end

  devise_for :users, :controllers => {:registrations => "users/registrations"}

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'users#index'

  resources :jobs do
    collection do
      get :autocomplete
    end
  end

  resources :pets
  get '/all', to: 'jobs#all', as: :all

  get '/secret', to: 'jobs#secret', as: :secret
  get '/show_all_jobs', to: 'jobs#show_all_jobs'

  resources :users, param: :slug do
    resources :chatrooms, only: [:index, :show, :create]
  end

  resources :messages, only:[:create]

end

app/models/job.rb
class Job < ApplicationRecord
  # we are creating a new method called owner that we can reference directly from the job to get us the ownerid.
  # b/c we have the same user_id as the same FK in the Jobs table, we had to specify the class name "User"
  # and we also had to specify the name of the FK. To do this we first had to create a new column in the migration with the new names of the FK and then add the reference to the FK.
  belongs_to :owner, :class_name => "User", :foreign_key => "owner_id", optional: true
  belongs_to :freelancer, :class_name => "User", :foreign_key => "freelancer_id", optional: true
  belongs_to :pet, optional: true
  searchkick word_start: [:title, :description, :city, :pet_breed, :status]

  def search_data
    {
      title: title,
      description: description,
      city: city,
      zip: zip,
      owner_name: owner.first_name,
      freelancer_name: freelancer.nil? ? "" : freelancer.first_name,
      pet_breed: pet.breed,
      status: status,
    }
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  # before_action :authenticate_user! will check if the user is authenticated before calling the secret method
  before_action :authenticate_user!, only: [:check_owner, :check_freelancer, :new, :create, :edit, :update, :destroy, :job_freelancer_params]
  before_action :find_job, only: [:edit, :show, :update, :destroy, :check_owner]
  before_action :check_owner, only: [:edit, :update, :destroy]



  def index

  end

  def all
    if params[:query].present?
      @jobs = Job.search(params[:query], page: params[:page], per_page: 5, misspellings: {below: 5}, where: {
        status: {not: 'Completed'}
        })
    else
      @jobs = []
    end
  end

  def autocomplete
    render json: Job.search(params[:query], {
        fields: ["title", "description", "city", "pet_breed"]
        }).map(&:title)
  end

  def show
    @job = Job.find_by_id(params[:id])
  end

  def show_all_jobs
    @jobs = Job.all.order(status: :desc, created_at: :desc)
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)
    if job_params["begin_date"].to_date < DateTime.now.to_date
        flash[:error] = "Job cannot start in the past. Please fix the dates and try again."
        render new_job_path(@job)
    else
      if job_params["end_date"].to_date >= job_params["begin_date"].to_date
        if @job.save
          redirect_to job_path(@job)
        else
          flash[:error] = "Sorry! We ran into an error - could you try again?"
        end
      else
        flash[:error] = "Job cannot end before it starts. Please fix the dates and try again."
        render new_job_path(@job)
      end
    end
  end

  def edit
    @job = Job.find_by_id(params[:id])
  end

  def update
    if (check_if_job_status_submitted_by_freelancer && check_if_job_is_freelancers_for_submission) || (check_if_job_status_submitted_by_freelancer && check_if_job_is_saved_to_db_by_freelancer == false)
      if @job.save
        # explode
        @job.update_attributes(job_freelancer_params)
        redirect_to job_path(@job)
      else
        flash[:error] = "Sorry! We ran into an error - could you try again?"
        render :edit
      end
    elsif check_if_job_status_submitted_by_freelancer == true && check_if_job_is_freelancers_for_submission != true
      flash[:error] = "Sorry! You can only update your own jobs!"
    end

    if check_if_job_is_subitted_owners
      # explode
      if job_params["begin_date"].to_date < DateTime.now.to_date
        # explode
          flash[:error] = "Job cannot start in the past. Please fix the dates and try again."
          render :edit
      elsif job_params["end_date"].to_date >= job_params["begin_date"].to_date
        # explode
          if @job.save
             @job.update_attributes(job_params)
             redirect_to job_path(@job)
          else
             flash[:error] = "Sorry! We ran into an error - could you try again?"
             render :edit
          end
      else
        flash[:error] = "Job cannot end before it starts. Please fix the dates and try again."
        render :edit
      end
    elsif check_if_job_status_submitted_by_freelancer == false && check_if_job_is_subitted_owners == false
      # explode
      if @job.save
        # explode
        @job.update_attributes(job_freelancer_params)
        redirect_to job_path(@job)
      else
        flash[:error] = "Sorry! We ran into an error - could you try again?"
        render :edit
      end
    end
  end

  def destroy
    if check_if_job_is_owners == true
      owner_slug = @job.owner.slug
      @job.destroy
      redirect_back(fallback_location: root_path)
    else
      flash[:error] = "Sorry! Only the owner can delete the job"
      redirect_to job_path(@job.id)
    end
  end



  private
  def job_params
    params.require(:job).permit(:title, :description, :owner_id, :city, :pet_id, :begin_date, :end_date, :status, :dollar_value)
  end
  def job_freelancer_params
    params.require(:job).permit(:status, :freelancer_id)
  end

  def check_owner
    if @job.freelancer.nil? #if the freelancer is empty is true
      if current_user.id.to_s != @job.owner.id.to_s #check to see if the current_id is the ower id if that is NOT true - then redirect them
        # explode
        # redirect_to edit_job_path(@job.id)
      end
    elsif current_user.id.to_s == @job.owner.id.to_s #check to see if the current_id is the freelancer's id if that is NOT true - if it they are equal let them edit
    elsif current_user.id.to_s != @job.freelancer.id.to_s
      redirect_to job_path(@job.id)
    end
  end

  # def update2
  #   if check_if_owner == true
  #
  #   if job_freelancer_params["freelancer_id"].nil?
  #     # no freelancer id means that job is open so do some checks
  #     if job_params["begin_date"].to_date < DateTime.now.to_date
  #         flash[:error] = "Job cannot start in the past. Please fix the dates"
  #         render :edit
  #     else
  #       if job_params["end_date"].to_date >= job_params["begin_date"].to_date
  #         if @job.save
  #           @job.update_attributes(job_params)
  #           redirect_to job_path(@job)
  #         else
  #           flash[:error] = "Sorry! We ran into an error - could you try again?"
  #           render :edit
  #         end
  #       else
  #         flash[:error] = "Job cannot end before the begin date. Please fix the dates and update again"
  #         render :edit
  #       end
  #     end
  #   elsif job_freelancer_params["freelancer_id"] == @job.freelancer.id
  #     if @job.save
  #       @job.update_attributes(job_freelancer_params)
  #       redirect_to job_path(@job)
  #     else
  #       flash[:error] = "Sorry! We ran into an error - could you try again?"
  #       render :edit
  #     end
  #     # redirect_to back
  #   # if the frelancer is trying update one that is not their own
  #   else
  #     flash[:error] = "Sorry! You can only edit your own jobs"
  #   end
  # end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_job_form.html.erb
<div>
  <%= f.label :title, "Name your job posting"%>
  <%= f.text_field :title, maxlength: 50, placeholder:"Need someone to watch Rocky!"%>
</div>
<div>
  <%= f.label :description, "Describe the work to be done"%>
  <%= f.text_field :description, maxlength: 1000, placeholder:"I need someone to be watch Rocky
  as night. Duties include: Feeding dinner, a walk around the block every
  2 hours, and giving medicine."%>
</div>
<% if @job.begin_date.nil? || @job.end_date.nil? %>
  <div>
    <%= f.label :begin_date, "Date for the job to start"%>
    <%= f.date_field :begin_date, :value => Date.today, min: Date.today %>
  </div>
<% else %>
  <div>
    <%= f.label :begin_date, "Date for the job to start"%>
    <%= f.date_field :begin_date, min: Date.today%>
  </div>
<% end %>
<div>
  <%= f.label :end_date, "Date for the job to end"%>
  <%= f.date_field :end_date, min: Date.today %>
</div>
<div>
  <%= f.label :dollar_value, "Dollar Value"%>
  <%= f.number_field :dollar_value, max: 1000 %>
</div>

<div>
  <%= f.label :city, "Location of job"%>
  <%= f.text_field :city, :value => current_user.city %>
</div>
  <%= f.label :pet_id, "Name of pet"%>
  <%= f.select :pet_id, current_user.pets.all.collect { |p| [ p.name, p.id ] }%>
  <%= hidden_field(:job, :owner_id, :value => current_user.id ) %>

app/views/jobs/_job_status_drop_down.html.erb
<% if @job.status == 'Open' %>
  <%= f.select :status, options_for_select(["Open", "In progress", "Completed"]) %>
<% elsif @job.status == 'In progress' %>
  <%= f.select :status, options_for_select(["In progress", "Open", "Completed"]) %>
<% else %>
  <%= f.select :status, options_for_select(["Completed", "Open", "In progress"]) %>
<% end %>

app/views/jobs/_job_summary.html.erb
<div class ="row job-class z-depth-5">
  <% if current_user &&                               #must be logged in
        (job.owner.id == current_user.id ||    #is owner
         job.freelancer_id.nil? ||             #jot still open
         job.freelancer_id == current_user.id) #is freelancer%>
    <div class="row">
      <div class="col s12 m12">
        <div class='right-align'>
          <%= link_to edit_job_path(job.id) do %>
            <i class="material-icons">edit</i>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>

  <div class="job-info-wrapper">
    <div class="row job-info-class">
      <div class="col s12 m4 l4">
        <b>Title: </b> <%= job.title %>
      </div>
      <div class="col s12 m4 l4">
        <b>Post Date: </b> <%= job.created_at.strftime("%m-%d-%Y") %>
      </div>
      <div class="col s12 m4 l4">
        <b>Begin Date: </b> <%= job.begin_date.strftime("%m-%d-%Y") %>
      </div>
    </div>
  </div>

  <div class="job-info-wrapper">
    <div class="row job-info-class">
      <div class="col s12 m8 l8">
        <b>City: </b> <%= job.city %>
      </div>

      <div class="col s12 m4 l3 ">
        <b>Status: </b>
        <span class="title job-status"> <%= job.status %></span>
      <!-- </div>
      <div class="col s1 m1 l1"> -->
        <i class="material-icons circle job-status
          <%= job.status == "Open" ? "green" :
              job.status == "In progress" ? "yellow" :
              job.status == "Completed" ? "red" : ""%>
          ">panorama_fish_eye</i>
      </div>
    </div>

    <div class="row">
      <div class="col s12 m12 l12">
        <b>Job Description: </b><%= job.description %>
      </div>
    </div>
  </div>

  <div class="job-info-wrapper">
    <div class="row">
      <div class="col s12 m12 l12">
        <div class='right-align'>
          <%= link_to "job details", job_path(job.id) %>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/jobs/_search_jobs.html.erb
<div class="container job-search center-align">
  <div class="row">
    <div style="margin: 0 auto; width: 50%;">
      <span class="search_header">Search Job Postings</span>

      <%= form_tag all_path, method: :get do %>
      <div class='form-group'>
        <%= text_field_tag :query, params[:query], class: 'form-control typeahead', placeholder: "Find the right job for you!" %>
        <%= submit_tag 'search', class: 'material-icons search_button' %>
      <% end %>
    </div>
  </div>
</div>

app/views/jobs/accept_job.html.erb
<p><strong>job.owner.id: </strong> <%= job.owner.id %> </p>
<p><strong>job.owner.id: </strong> <%= job.owner.first_name %> </p>
<% if job.freelancer.nil? %>
<% else %>
<p><strong>job.freelancer.id: </strong> <%= job.freelancer.id %> </p>
<% end %>
<p><strong>Title: </strong> <%= job.title %> </p>
<p><strong>Description: </strong> <%= job.description %> </p>
<p><strong>Address: </strong> <%= job.address %> </p>
<p><strong>City: </strong> <%= job.city %> </p>
<p><strong>State: </strong> <%= job.state %> </p>
<p><strong>Zip: </strong> <%= job.zip %> </p>
<p><strong>Begin Date: </strong> <%= job.begin_date %> </p>
<p><strong>End Date: </strong> <%= job.end_date %> </p>
<p><strong>Dollar Value: </strong> <%= job.dollar_value %> </p>
<p><strong>Type of Job: </strong> <%= job.type_of_job %> </p>
<p><strong>Status: </strong> <%= job.status %> </p>
</div>

app/views/jobs/all.html.erb
<!-- <div class="container"> -->
<%= render 'search_jobs'%>

<% if @jobs.empty? %>
  <h1> Nothing matched your search request, try again </h1>
<% else %>

    <% @jobs.each do |job| %>
    <%= render partial: "job_summary", locals: { job: job } %>
<% end %>

    <%= paginate @jobs %>
    <div class="pagination_page_info">
      <%= page_entries_info @jobs %>
    </div>
  <!-- </div> -->
<% end %>

app/views/jobs/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col s12">
      <% if check_if_job_is_owners %>
        <h1>Hey, <%= @job.owner.first_name %>! Weclome back to your job posting</h1>
        <p>Please update your job!</p>
        <%= form_for @job do |f| %>
          <%= render partial: "job_form", locals: { f: f } %>
          <%= hidden_field(:job, :status, :value => 'Open' ) %>
          <%= f.label :status, "Status of Job"%>
          <%= render partial: "job_status_drop_down", locals: { f: f } %>
          <%= f.submit "Update Job", class: "btn" %>
        <% end %>
      <% elsif check_if_job_is_saved_to_db_by_freelancer == false %>
        <h1>If you want to work on this job, change update the status below!</h1>
        <%= form_for @job do |f| %>
          <%= f.label :status, "Status of Job"%>
          <%= render partial: "job_status_drop_down", locals: { f: f } %>
          <%= hidden_field(:job, :freelancer_id, :value => current_user.id ) %>
          <%= f.submit "Update Status", class: "btn" %>
        <% end %>
      <% elsif check_if_job_is_freelancers == true %>
          <h1>Hey, <%= @job.freelancer.first_name %>! Update the status of the job.</h1>
          <%= form_for @job do |f| %>
            <%= f.label :status, "Status of Job"%>
            <%= render partial: "job_status_drop_down", locals: { f: f } %>
            <%= hidden_field(:job, :freelancer_id, :value => current_user.id ) %>
            <%= f.submit "Update Status", class: "btn" %>
          <% end %>
      <% end %>


    </div>
  </div>
</div>

app/views/jobs/index.html.erb
<div class="container">
  <div class="row">
    <div class="col s12">
      <% @job.each do |job| %>
        <h1> <%= job.title %> </h1>
        <hr>
        <p><strong>ID: </strong> <%= job.id %> </p>
        <hr>
        <p><strong>Description: </strong> <%= job.description %> </p>
        <hr>
        <p><strong>Address: </strong> <%= job.address %> </p>
        <hr>
        <p><strong>City: </strong> <%= job.city %> </p>
        <hr>
        <p><strong>State: </strong> <%= job.state %> </p>
        <hr>
        <p><strong>Zip: </strong> <%= job.zip %> </p>
        <hr>
        <p><strong>Begin Date: </strong> <%= job.begin_date %> </p>
        <hr>
        <p><strong>End Date: </strong> <%= job.end_date %> </p>
        <hr>
        <p><strong>Dollar Value: </strong> <%= job.dollar_value %> </p>
        <hr>
        <p><strong>Type of Job: </strong> <%= job.type_of_job %> </p>
        <hr>
        <p><strong>Status: </strong> <%= job.status %> </p>
        <hr>
        <p><strong>Recurring: </strong> <%= job.recurring %> </p>
        <hr>
        <p><strong>Pet Location: </strong> <%= job.pet_location %> </p>
        <hr>
        <p><strong>Expiration Date: </strong> <%= job.expiration_date %> </p>
        <hr>
        <p><strong>Job Owner: </strong> <%= job.owner.first_name %> <%= job.owner.last_name %> </p>
        <hr>
        <p><strong>Name of pet: </strong> <%= job.pet.name %>
        <hr>
      <% end %>
    </div>
  </div>
</div>

app/views/jobs/new.html.erb
<div class="container">
  <div class="row">
    <div class="col s12">
      <h1>Create a new job</h1>
        <%= form_for @job do |f| %>
          <%= render partial: "job_form", locals: { f: f } %>
          <%= hidden_field(:job, :status, :value => 'Open' ) %>
          <%= f.submit "Post Job", class: "btn" %>
        <% end %>
    </div>
  </div>
</div>

app/views/jobs/ray.html.erb
<div class=job-section>
  <% if @jobs.length != 0 %>
    <div class="container">
      <div class="row">
        <h5> All Job Posting </h5>
      </div>
    </div>

    <div class="container job-container">
      <% @jobs.each do |job| %>
        <div class ="row job-class">
          <div class="row">
            <div class="col s12 m12">
              <div class='right-align'>
                <%= link_to edit_job_path(job.id) do %>
                  <i class="material-icons">edit</i>
                <% end %>
              </div>
            </div>
          </div>

          <div class="job-info-wrapper">
            <div class="row job-info-class">
              <div class="col s12 m8 l8">
                <b>Title: </b> <%= job.title %>
              </div>
              <div class="col s12 m4 l4">
                <b>Post Date: </b> <%= job.created_at.strftime("%m-%d-%Y") %>
              </div>
            </div>
          </div>

          <div class="job-info-wrapper">
            <div class="row job-info-class">
              <div class="col s12 m4 l4">
                <b>City: </b> <%= job.city %>
              </div>

              <div class="col s12 m4 l4">
                <b>Type of Job: </b> <%= job.type_of_job %>
              </div>

              <div class="col s12 m4 l4">
                <b>Dollar Value: </b> <%= job.dollar_value %>
                <% num = job.dollar_value <= 25 ? 1 : (job.dollar_value/25).round %>
                <% num = num > 4 ? 4 : num %>
                <% num.times do %>
                   <i class="material-icons green">attach_money</i>
                <% end %>
              </div>

            </div>
          </div>

          <div class="job-info-wrapper">
            <div class="row job-info-class">
              <div class="col s12 m4 l4">
                <b>Begin Date: </b> <%= job.begin_date.strftime("%m-%d-%Y") %>
              </div>
              <div class="col s12 m4 l4">
                <b>End Date: </b> <%= job.end_date.strftime("%m-%d-%Y") %>
              </div>
              <div class="col s12 m4 l4">
                <b>Recurring: </b> <%= job.recurring %>
              </div>
            </div>
          </div>

          <div class="job-info-wrapper">
            <b>Job Description: </b><%= job.description %>
            <div class="row job-info-class">
              <div class="col s6 m8 l8 ">
                <b>Status: </b>
                <span class="title job-status"> <%= job.status %></span>
                <i class="material-icons circle job-status
                  <%= job.status == "posted" ? "red" :
                      job.status == "in progress" ? "yellow" :
                      job.status == "completed" ? "green" : ""%>
                  ">panorama_fish_eye</i>
              </div>

              <div class="col s12 m4 l4">
                <div class="row">
                  <div class="col s12 m12 l12">
                    <b>Owner: </b> <%= job.owner.first_name %> <%= job.owner.last_name %>
                  </div>
                  <div class="col s12 m12 l12">
                    <b>Freelancer: </b> <%= job.freelancer.first_name %> <%= job.freelancer.last_name %>
                  </div>
                </div>
              </div>

            </div>
          </div>

        </div>
      <% end %>

      <% if @jobs.length > 3 %>
        <div class="show more">Show More</div>
        <div class="show less">Show Less</div>
      <% end %>
    </div>
  <% else %>
    <div class="container">
      <h5>You have no job posted yet</h5>
    </div>
  <% end %>
</div>

app/views/jobs/secret.html.erb
SECRET

app/views/jobs/show.html.erb
<div class=job-section>
    <div class="container">
      <div class="row">
        <h5> Job Details </h5>
      </div>
    </div>

    <div class="container job-container">
        <div class ="row job-class z-depth-5">
          <% if current_user &&                      #must be logged in
              (@job.owner.id == current_user.id ||    #is owner
               @job.freelancer_id.nil? ||             #jot still open
               @job.freelancer_id == current_user.id) #is freelancer %>
            <div class="row">
              <div class="col s12 m12">
                <div class='right-align'>
                  <%= link_to edit_job_path(@job.id) do %>
                    <i class="material-icons">edit</i>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>

          <div class="job-info-wrapper">
            <div class="row job-info-class">
              <div class="col s12 m8 l8">
                <b>Title: </b> <%= @job.title %>
              </div>
              <div class="col s12 m4 l4">
                <b>Post Date: </b> <%= @job.created_at.strftime("%m-%d-%Y") %>
              </div>
            </div>
          </div>

          <div class="job-info-wrapper">
            <div class="row job-info-class">
              <div class="col s12 m4 l4">
                <b>City: </b> <%= @job.city %>
              </div>

              <div class="col s12 m4 l4">
                <b>Type of Job: </b> <%= @job.type_of_job %>
              </div>

              <div class="col s12 m4 l4">
                <b>Dollar Value: </b>
                <% if @job.dollar_value %>
                  <%= @job.dollar_value %>
                  <% num = @job.dollar_value <= 25 ? 1 : (@job.dollar_value/25).round %>
                  <% num = num > 4 ? 4 : num %>
                  <span class="green-dollar"> <%= "$" * num %> </span>
                <% end %>
              </div>

            </div>
          </div>

          <div class="job-info-wrapper">
            <div class="row job-info-class">
              <div class="col s12 m4 l4">
                <b>Begin Date: </b> <%= @job.begin_date.strftime("%m-%d-%Y") %>
              </div>
              <div class="col s12 m4 l4">
                <b>End Date: </b> <%= @job.end_date.strftime("%m-%d-%Y") %>
              </div>
              <div class="col s12 m4 l4">
                <b>Recurring: </b> <%= @job.recurring %>
              </div>
            </div>
          </div>

          <div class="job-info-wrapper">
            <b>Job Description: </b><%= @job.description %>
            <div class="row job-info-class">
              <div class="col s6 m8 l8 ">
                <b>Status: </b>
                <span class="title job-status"> <%= @job.status %></span>
                <i class="material-icons circle job-status
                  <%= @job.status == "Open" ? "green" :
                      @job.status == "In progress" ? "yellow" :
                      @job.status == "Completed" ? "red" : ""%>
                  ">panorama_fish_eye</i>
              </div>

              <div class="col s12 m4 l4">
                <div class="row">
                  <div class="col s12 m12 l12">
                    <b>Owner: </b> <%= @job.owner.first_name %> <%= @job.owner.last_name %>
                  </div>
                  <div class="col s12 m12 l12">
                    <% if !@job.freelancer.nil? %>
                      <b>Freelancer: </b> <%= @job.freelancer.first_name %> <%= @job.freelancer.last_name %>
                    <% else %>
                      <b>Freelancer: </b> None
                    <% end %>
                  </div>
                </div>
              </div>

            </div>
          </div>

        </div>
    </div>
</div>

app/views/jobs/show_all_jobs.html.erb
<div class=job-section>
  <% if @jobs.length != 0 %>
    <div class="container">
      <div class="row">
        <h5> All Job Posting </h5>
      </div>
    </div>

    <div class="container job-container">
      <% @jobs.each do |job| %>
        <div class ="row job-class">
          <% if current_user &&                      #must be logged in
              (job.owner.id == current_user.id ||    #is owner
               job.freelancer_id.nil? ||             #jot still open
               job.freelancer_id == current_user.id) #is freelancer %>
            <div class="row">
              <div class="col s12 m12">
                <div class='right-align'>
                  <%= link_to edit_job_path(job.id) do %>
                    <i class="material-icons">edit</i>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>

          <div class="job-info-wrapper">
            <div class="row job-info-class">
              <div class="col s12 m8 l8">
                <b>Title: </b> <%= job.title %>
              </div>
              <div class="col s12 m4 l4">
                <b>Post Date: </b> <%= job.created_at.strftime("%m-%d-%Y") %>
              </div>
            </div>
          </div>

          <div class="job-info-wrapper">
            <div class="row job-info-class">
              <div class="col s12 m4 l4">
                <b>City: </b> <%= job.city %>
              </div>

              <div class="col s12 m4 l4">
                <b>Type of Job: </b> <%= job.type_of_job %>
              </div>

              <div class="col s12 m4 l4">
                <b>Dollar Value: </b>
                <% if job.dollar_value %>
                  <%= job.dollar_value %>
                  <% num = job.dollar_value <= 25 ? 1 : (job.dollar_value/25).round %>
                  <% num = num > 4 ? 4 : num %>
                  <span class="green-dollar">
                    <%= "$" * num %>
                  </span>
                <% end %>
              </div>

            </div>
          </div>

          <div class="job-info-wrapper">
            <div class="row job-info-class">
              <div class="col s12 m4 l4">
                <b>Begin Date: </b> <%= job.begin_date.strftime("%m-%d-%Y") %>
              </div>
              <div class="col s12 m4 l4">
                <b>End Date: </b> <%= job.end_date.strftime("%m-%d-%Y") %>
              </div>
              <div class="col s12 m4 l4">
                <b>Recurring: </b> <%= job.recurring %>
              </div>
            </div>
          </div>

          <div class="job-info-wrapper">
            <b>Job Description: </b><%= job.description %>
            <div class="row job-info-class">
              <div class="col s6 m8 l8 ">
                <b>Status: </b>
                <span class="title job-status"> <%= job.status %></span>
                <i class="material-icons circle job-status
                  <%= job.status == "Open" ? "green" :
                      job.status == "In progress" ? "yellow" :
                      job.status == "Completed" ? "red" : ""%>
                  ">panorama_fish_eye</i>
              </div>

              <div class="col s12 m4 l4">
                <div class="row">
                  <div class="col s12 m12 l12">
                    <b>Owner: </b> <%= job.owner.first_name %> <%= job.owner.last_name %>
                  </div>
                  <div class="col s12 m12 l12">
                    <% if !job.freelancer.nil? %>
                      <b>Freelancer: </b> <%= job.freelancer.first_name %> <%= job.freelancer.last_name %>
                    <% else %>
                      <b>Freelancer: </b> None
                    <% end %>
                  </div>
                </div>
              </div>

            </div>
          </div>

        </div>
      <% end %>

      <% if @jobs.length > 3 %>
        <div class="show more">Show More</div>
        <div class="show less">Show Less</div>
      <% end %>
    </div>
  <% else %>
    <div class="container">
      <h5>You have no job posted yet</h5>
    </div>
  <% end %>
</div>