config/routes.rb
Rails.application.routes.draw do
  ### chat start
  # Mount the Action Cable server on a sub-URI of our main application.
  # Action Cable will be listening for WebSocket requests on ws://localhost:3000/cable. It will do so by using the Rack socket hijacking API. When our main application is instantiated, an instance of Action Cable will also be created. Action Cable will, per our instructions in the routes.rb file, establish a WebSocket connection on localhost:3000/cable, and begin listening for socket requests on that URI.
  mount ActionCable.server => '/cable'
  ### chat end

  devise_for :users, :controllers => {:registrations => "users/registrations"}

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'users#index'

  resources :jobs do
    collection do
      get :autocomplete
    end
  end

  resources :pets
  get '/all', to: 'jobs#all', as: :all

  get '/secret', to: 'jobs#secret', as: :secret
  get '/show_all_jobs', to: 'jobs#show_all_jobs'

  resources :users, param: :slug do
    resources :chatrooms, only: [:index, :show, :create]
  end

  resources :messages, only:[:create]

end

app/models/user.rb
class User < ApplicationRecord
  # B/c two one-to-many relationship with the user_ID acting as the two FKs in the jobs table we had to further specify the class name and the actual name of the FK in the jobs table

  has_many :posted_jobs, :class_name => "Job", :foreign_key => "owner_id", dependent: :destroy
  has_many :working_jobs, :class_name => "Job", :foreign_key => "freelancer_id", dependent: :destroy
  # the dependent destroy is saying that when the user goes away the job goes away
  has_many :pets, dependent: :destroy
  # user has many pets - so if the user gets deleted so their pets

  # user can have many messages and many chatrooms through subscriptions since a user can have many chats
  has_many :messages, dependent: :destroy
  has_many :subscriptions
  has_many :chatrooms, through: :subscriptions

  # Include default devise modules. Others available are:
  # :confirmable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
  :lockable

  mount_uploader :image, ProfileUploader

  # use email address to make slug unique
  include FriendlyId
  friendly_id :first_name_and_last_name, use: [:finders, :slugged]
  # creation of the friendly_id for the urls
  def first_name_and_last_name
    "#{first_name}-#{last_name}"
  end

  def existing_chatrooms_users
    existing_chatroom_users = []
      self.chatrooms.each do |chatroom|
        existing_chatroom_users.concat(chatroom.subscriptions.where.not(user_id: self.id).map {|subscription| subscription.user})
      end
    existing_chatroom_users.uniq
  end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :about_me, :address, :city, :state, :zip ])
  # end
  #
  # end
  # # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :about_me, :address, :city, :state, :zip ])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  def after_update_path_for(resource_or_scope)
    user_path(resource_or_scope)
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update]
  before_action :find_user, only: [:edit, :show, :update]

  def show
    @pets = @user.pets
    @posted_jobs = @user.posted_jobs.order(created_at: :desc)
    @working_jobs = @user.working_jobs.order(created_at: :desc)
  end

  def find_user
    @user = User.friendly.find(params[:slug])
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user_has_picture.html.erb
<% if @user.image.nil? %>
  <%= image_tag(asset_path('default_user_no_image.png'), class: "circle") %>
<% else %>
  <%= image_tag(@user.image_url.to_s, class: "circle") %>
<% end %>

app/views/users/index.html.erb
<div class="container center-align">
    <h1 class="center-align">Welcome to PetWork</h1>
      <div class= "slider">
        <ul class="slides">
          <li>
            <img class="puppy center-align" src="https://static.pexels.com/photos/275717/pexels-photo-275717.jpeg">
          </li>
          <li>
            <img class="puppy center-align" src="https://static.pexels.com/photos/356378/pexels-photo-356378.jpeg">
          </li>
          <li>
            <img class="puppy center-align" src="http://cdn.akc.org/cavalier-puppy-leash-training.jpg">
          </li>
        </ul>
      </div>
</div>
    <br>
    <br>
  <div>
    <p class="center-align">
      <%= link_to 'Register', new_user_registration_path, class: 'btn btn-lg waves-effect' %>
    </p>
</div>
  <div class="container">
    <div class="center-align col l12 m12 s12">
      <%= render '/jobs/search_jobs'%>
    </div>
  </div>

<div class="row">
  <div class="center-align col l6 m6 s12">
    <br>
    <br>
    <br>
    <h3 class="mission">Mission Statement</h3>
    <h6>PetWork is committed to bringing people together to help pet owners take care of their
      pets.</h6>
    <br>
    <!-- <img class="mission_dog" src="https://www.cheatsheet.com/wp-content/uploads/2017/04/Beautiful-dog-rhodesian-ridgeback-puppy.jpg"> -->
    <br>
  </div>
  <div class="center-align col l6 m6 s12">
    <br>
    <br>
    <br>
    <h3 class="customerex">Customer Experience</h3>
    <h6>I signed up with PetWork because I needed help with my dog when I started a new job.
    Working with them has been a great experience! All the freelancers I have worked with have
    been wonderful and well qualified. I recommend them to anyone I can.
    -John Smith
    </h6>
    <br>
    <!-- <img class="customer_dog" src="https://s3-media4.fl.yelpcdn.com/buphoto/Y7bANmtYpuuH7axUASoc7A/o.jpg"> -->
    <br>
  </div>
</div>

app/views/users/show.html.erb
<!-- Start of Profile -->
<div class="user-section">
  <div class="container">
    <div class="row z-depth-5">
      <div class="col s4 offset-s4 m4 offset-m4">
        <br>
        <%= image_tag(@user.image_url(:thumb).to_s, class: "circle prof-image") %>

      </div>
      <div class="col s12 m10 offset-m1 prof-info user-class">
        <% if current_user && (@user.id == current_user.id) %>
          <div class='right-align'>
            <%= link_to edit_user_registration_path(current_user) do %>
              <i class="material-icons">edit</i>
            <% end %>
          </div>
        <% end %>
        <div class="user-info-wrapper">
          <div class="row user-info-class">
            <div class="col s10 m6 l5 xl4">
              <b>Name: </b><%= @user.first_name.upcase %> <%= @user.last_name.upcase %> <br>
            </div>
            <div class="col s10 m6 l5 xl4">
              <b>Location: </b><%= @user.city %> <br>
            </div>
            <div class="col s10 m6 l5 xl4">
              <b>Date Joined: </b><%= @user.created_at.strftime("%B").to_s + " " + @user.created_at.year.to_s %></p>
            </div>
          </div>
        </div>
        <b>About Me: </b><%= @user.about_me %> <br><br>

      </div>
    </div>
    <div class="container">
        <div class="center-align">
            <span class="profile-button"><%= link_to 'Add Pet', new_pet_path, class: 'btn btn-lg' %>
            </span> <span class="profile-button"><%= link_to 'Add Job', new_job_path, class: 'btn btn-lg' %>
            </span><span class="profile-button"><%= link_to 'Chat', user_chatrooms_path(current_user), class: 'btn btn-lg' %>
            </span>
        </div>
      </div>
  </div>
</div>
<!-- end profile -->

<div class="pet-section">
  <% if @pets.length != 0 %>
    <div class="container">
      <div class="row">
        <h5> My Pets </h5>
      </div>
    </div>

    <div class="container pet-container">
      <% @pets.each do |pet| %>
        <div class="row pet-class">
          <div class="col s12 m4">
            <%= image_tag(pet.image, class:'pet-image z-depth-5') %>
          </div>

          <div class="col s12 m8 z-depth-5 user-pet">
            <% if current_user && (@user.id == current_user.id) %>
              <div class='right-align'>
                <%= link_to edit_pet_path(pet.id) do %>
                  <i class="material-icons">edit</i>
                <% end %>
                  <%= link_to material_icon.delete, pet, :url => "/pets/#{pet.id}", method: :delete, data: { confirm: 'Are you sure?' } %>
              </div>
            <% end %>
            <div class="pet-info-wrapper">
              <div class=" row pet-info-class">
                <div class="col s12 m4 l5">
                  <b>Name: </b><%= pet.name %>
                </div>
                <div class="col s12 m5 l5">
                  <b>Breed: </b><%= pet.breed %>
                </div>
                <div class="col s12 m3 l2">
                  <b>Age: </b><%= pet.age %>
                </div>
              </div>
              <b>About <%= pet.name %>: </b><%= pet.about_me %>
            </div>
          </div>

        </div>
      <% end %>

      <% if @pets.length > 3 %>
        <div class="show more">Show More</div>
        <div class="show less">Show Less</div>
      <% end %>
    </div>

  <% else %>
    <div class="container">
      <h5>No Pets Yet</h5>
    </div>
  <% end %>
</div>

<!-- Start of jobs where they are the owner -->
<div class=posted_job-section>
  <% if @posted_jobs.length != 0 %>
    <div class="container">
      <div class="row">
        <h5> My Posted Jobs</h5>
      </div>
    </div>

    <div class="container posted_job-container">
      <% @posted_jobs.each do |posted_job| %>
        <div class ="row job-class z-depth-5">
          <% if current_user &&                               #must be logged in
                (posted_job.owner.id == current_user.id ||    #is owner
                 posted_job.freelancer_id.nil? ||             #jot still open
                 posted_job.freelancer_id == current_user.id) #is freelancer%>
            <div class="row">
              <div class="col s12 m12">
                <div class='right-align'>
                  <%= link_to edit_job_path(posted_job.id) do %>
                    <i class="material-icons">edit</i>
                  <% end %>
                  <%= link_to material_icon.delete, posted_job, :url => "/jobs/#{posted_job.id}", method: :delete, data: { confirm: "Are you sure you want to delete the #{posted_job.title} job?" } %>
                </div>
              </div>
            </div>
          <% end %>

          <div class="job-info-wrapper">
            <div class="row job-info-class">
              <div class="col s12 m4 l4">
                <b>Title: </b> <%= posted_job.title %>
              </div>
              <div class="col s12 m4 l4">
                <b>Post Date: </b> <%= posted_job.created_at.strftime("%m-%d-%Y") %>
              </div>
              <div class="col s12 m4 l4">
                <b>Begin Date: </b> <%= posted_job.begin_date.strftime("%m-%d-%Y") %>
              </div>
            </div>
          </div>

          <div class="job-info-wrapper">
            <div class="row job-info-class">
              <div class="col s12 m8 l8">
                <b>City: </b> <%= posted_job.city %>
              </div>

              <div class="col s12 m4 l3 ">
                <b>Status: </b>
                <span class="title job-status"> <%= posted_job.status %></span>
              <!-- </div>
              <div class="col s1 m1 l1"> -->
                <i class="material-icons circle job-status
                  <%= posted_job.status == "Open" ? "green" :
                      posted_job.status == "In progress" ? "yellow" :
                      posted_job.status == "Completed" ? "red" : ""%>
                  ">panorama_fish_eye</i>
              </div>
            </div>

            <div class="row">
              <div class="col s12 m12 l12">
                <b>Job Description: </b><%= posted_job.description.truncate(200) %>
              </div>
            </div>
          </div>

          <div class="job-info-wrapper">
            <div class="row">
              <div class="col s12 m12 l12">
                <div class='right-align'>
                  <%= link_to "job details", job_path(posted_job.id) %>
                </div>
              </div>
            </div>
          </div>

        </div>
      <% end %>

      <% if @posted_jobs.length > 3 %>
        <div class="show more">Show More</div>
        <div class="show less">Show Less</div>
      <% end %>
    </div>
  <% else %>
    <div class="container">
      <h5>You Have Not Posted Any Jobs</h5>
    </div>
  <% end %>
</div>

<!-- Start of jobs where they are the freelancer -->
<div class=working_job-section>
  <% if @working_jobs.length != 0 %>
    <div class="container">
      <div class="row">
        <h5> My Working Jobs </h5>
      </div>
    </div>

    <div class="container working_job-container">
      <% @working_jobs.each do |working_job| %>
        <div class ="row job-class z-depth-5">
          <% if current_user &&                              #must be logged in
              (working_job.owner.id == current_user.id ||    #is owner
               working_job.freelancer_id.nil? ||             #jot still open
               working_job.freelancer_id == current_user.id) #is freelancer %>
            <div class="row">
              <div class="col s12 m12">
                <div class='right-align'>
                  <%= link_to edit_job_path(working_job.id) do %>
                    <i class="material-icons">edit</i>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>

          <div class="job-info-wrapper">
            <div class="row job-info-class">
              <div class="col s12 m4 l4">
                <b>Title: </b> <%= working_job.title %>
              </div>
              <div class="col s12 m4 l4">
                <b>Post Date: </b> <%= working_job.created_at.strftime("%m-%d-%Y") %>
              </div>
              <div class="col s12 m4 l4">
                <b>Begin Date: </b> <%= working_job.begin_date.strftime("%m-%d-%Y") %>
              </div>
            </div>
          </div>

          <div class="job-info-wrapper">
            <div class="row job-info-class">
              <div class="col s5 m8 l8">
                <b>City: </b> <%= working_job.city %>
              </div>

              <div class="col s6 m4 l3 ">
                <b>Status: </b>
                <span class="title job-status"> <%= working_job.status %></span>
                <i class="material-icons circle job-status
                  <%= working_job.status == "Open" ? "green" :
                      working_job.status == "In progress" ? "yellow" :
                      working_job.status == "Completed" ? "red" : ""%>
                  ">panorama_fish_eye</i>
              </div>
            </div>
            <b>Job Description: </b><%= working_job.description.truncate(100) %>
          </div>

          <div class="job-info-wrapper">
            <div class="row">
              <div class="col s12 m12 l12">
                <div class='right-align'>
                  <%= link_to "job details", job_path(working_job.id) %>
                </div>
              </div>
            </div>
          </div>

        </div>
      <% end %>

      <% if @working_jobs.length > 3%>
        <div class="show more">Show More</div>
        <div class="show less">Show Less</div>
      <% end %>

    </div>
  <% else %>
    <div class="container">
      <h5>You have not taken any job yet</h5>
    </div>
  <% end %>
</div>
<br>